using System.Collections.Generic;
using UnityEngine;

namespace FishingIdle.Game.Audio
{
    /// <summary>
    /// The game's sounds, loaded by name from Assets/Resources/Sons. Replacing a file there with a real
    /// recording of the same name changes the sound without touching code. A missing file is simply
    /// silent. The current files are generated by tools/Audio/gerar_sons.py.
    /// </summary>
    public static class SoundBank
    {
        private static readonly Dictionary<string, AudioClip> Clips = new Dictionary<string, AudioClip>();

        public static AudioClip For(SoundCue cue)
        {
            return Load(FileFor(cue));
        }

        /// <summary>A clip by file name (without extension), or null when the file is missing.</summary>
        public static AudioClip Load(string file)
        {
            if (string.IsNullOrEmpty(file))
            {
                return null;
            }

            // "clip == null" also catches a clip Unity unloaded when play mode ended.
            if (!Clips.TryGetValue(file, out var clip) || clip == null)
            {
                clip = Resources.Load<AudioClip>("Sons/" + file);
                Clips[file] = clip;
            }

            return clip;
        }

        public static string FileFor(SoundCue cue)
        {
            switch (cue)
            {
                case SoundCue.Click: return "clique";
                case SoundCue.Catch: return "captura";
                case SoundCue.RareCatch: return "captura_rara";
                case SoundCue.Record: return "recorde";
                case SoundCue.LevelUp: return "subir_nivel";
                case SoundCue.Coins: return "moedas";
                case SoundCue.Important: return "importante";
                case SoundCue.Warning: return "aviso";
                default: return null;
            }
        }
    }
}
