using System.Collections.Generic;
using UnityEngine;

namespace FishingIdle.Game.Visual
{
    /// <summary>
    /// Loads the replaceable art files in Assets/Resources/Arte by name (Art Bible, sections 35–37).
    /// </summary>
    /// <remarks>
    /// Every image the game shows is a file that can be swapped for final art keeping its name;
    /// nothing is wired into scene logic. A missing file returns null, and each caller falls back to
    /// the art generated from code, so the game never breaks because an asset is absent.
    /// </remarks>
    public static class ArtAssets
    {
        private static readonly Dictionary<string, Texture2D> Textures = new Dictionary<string, Texture2D>();
        private static readonly Dictionary<string, Sprite> Sprites = new Dictionary<string, Sprite>();

        /// <summary>A texture under Resources/Arte (path without extension), or null.</summary>
        public static Texture2D Texture(string path)
        {
            // A missing file is remembered as null, so it is looked up only once.
            if (Textures.TryGetValue(path, out var cached))
            {
                return cached;
            }

            var tex = Resources.Load<Texture2D>("Arte/" + path);
            if (tex != null)
            {
                tex.wrapMode = TextureWrapMode.Clamp;
            }

            Textures[path] = tex;
            return tex;
        }

        /// <summary>A sprite made from a texture under Resources/Arte, <paramref name="unitsWide"/> world units across.</summary>
        public static Sprite Sprite(string path, float unitsWide, Vector2 pivot)
        {
            var key = path + "|" + unitsWide + "|" + pivot;
            if (Sprites.TryGetValue(key, out var cached) && cached != null)
            {
                return cached;
            }

            var tex = Texture(path);
            if (tex == null)
            {
                return null;
            }

            var sprite = UnityEngine.Sprite.Create(tex, new Rect(0, 0, tex.width, tex.height), pivot, tex.width / unitsWide, 0, SpriteMeshType.FullRect);
            sprite.name = path;
            sprite.hideFlags = HideFlags.DontSave;
            Sprites[key] = sprite;
            return sprite;
        }

        /// <summary>A sprite made from a texture under Resources/Arte, <paramref name="unitsTall"/> world units high (the width follows the picture).</summary>
        public static Sprite SpriteByHeight(string path, float unitsTall, Vector2 pivot)
        {
            var tex = Texture(path);
            return tex == null ? null : Sprite(path, unitsTall * tex.width / tex.height, pivot);
        }

        /// <summary>An interface icon (Resources/Arte/Icones/ico_&lt;name&gt;.png). Use the names in <see cref="Icons"/>.</summary>
        public static Texture2D Icon(string name) => Texture("Icones/ico_" + name);
    }

    /// <summary>Names of the icon files (the family generated by tools/Arte/gerar_icones.py).</summary>
    public static class Icons
    {
        public const string Fishing = "pesca", Map = "mapa", Aquarium = "aquario", Arena = "arena", Expedition = "expedicao",
            Market = "mercado", Shop = "loja", Profile = "perfil", Bell = "avisos", Settings = "opcoes", Close = "fechar",
            Play = "iniciar", Stop = "parar", Star = "estrela", Rod = "vara", Fish = "peixe", Book = "especies",
            Pin = "local", Clock = "relogio", Lock = "cadeado", Check = "confirmar", Energy = "energia", Honor = "honra",
            Chevron = "seta", Arrow = "seta_longa", Add = "adicionar", Box = "caixa", Sell = "vender", Attack = "atacar",
            Swap = "trocar", Ranking = "ranking", Info = "info", Warning = "aviso", Hourglass = "ampulheta", Level = "nivel",
            Buy = "comprar", Sort = "ordenar", Feed = "alimentar", Home = "inicio", Waves = "ondas", Compact = "compacto",
            Coin = "moeda", Shell = "concha", Pause = "pausa", Search = "buscar", Boat = "barco", Bait = "isca";
    }
}
