// <auto-generated />
using System;
using FishingIdle.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FishingIdle.Api.Persistence.Migrations
{
    [DbContext(typeof(FishingIdleDbContext))]
    partial class FishingIdleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FishingIdle.Api.Persistence.Entities.AdminAuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_admin_id");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit_log");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_admin_audit_log_occurred_at_utc");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_admin_audit_log_target_type_target_id");

                    b.ToTable("admin_audit_log", (string)null);
                });

            modelBuilder.Entity("FishingIdle.Api.Persistence.Entities.ConfigVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_config_versions");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_config_versions_is_active")
                        .HasFilter("is_active");

                    b.HasIndex("VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_config_versions_version_number");

                    b.ToTable("config_versions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
